version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: clean
      MONGO_INITDB_ROOT_PASSWORD: project

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: clean
      ME_CONFIG_MONGODB_ADMINPASSWORD: project
